package com.optum.svc.bean;

public class SvcBean {
	private String PROCESS_DATE1;                                 
	private int LOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES;     
	private int LOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES;      
	private int PENDING_PRADJD_CLAIMS;                       
	private String PROCESS_DATE2;                                 
	private int LOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES;   
	private int LOADED_TO_ADJD_SERVICE_CHANNEL_TABLES;        
	private int PENDING_ADJD_CLAIMS;
	
	public String getPROCESS_DATE1() {
		return PROCESS_DATE1;
	}
	public void setPROCESS_DATE1(String pROCESS_DATE1) {
		PROCESS_DATE1 = pROCESS_DATE1;
	}
	public int getLOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES() {
		return LOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES;
	}
	public void setLOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES(int lOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES) {
		LOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES = lOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES;
	}
	public int getLOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES() {
		return LOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES;
	}
	public void setLOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES(int lOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES) {
		LOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES = lOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES;
	}
	public int getPENDING_PRADJD_CLAIMS() {
		return PENDING_PRADJD_CLAIMS;
	}
	public void setPENDING_PRADJD_CLAIMS(int pENDING_PRADJD_CLAIMS) {
		PENDING_PRADJD_CLAIMS = pENDING_PRADJD_CLAIMS;
	}
	public String getPROCESS_DATE2() {
		return PROCESS_DATE2;
	}
	public void setPROCESS_DATE2(String pROCESS_DATE2) {
		PROCESS_DATE2 = pROCESS_DATE2;
	}
	public int getLOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES() {
		return LOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES;
	}
	public void setLOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES(int lOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES) {
		LOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES = lOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES;
	}
	public int getLOADED_TO_ADJD_SERVICE_CHANNEL_TABLES() {
		return LOADED_TO_ADJD_SERVICE_CHANNEL_TABLES;
	}
	public void setLOADED_TO_ADJD_SERVICE_CHANNEL_TABLES(int lOADED_TO_ADJD_SERVICE_CHANNEL_TABLES) {
		LOADED_TO_ADJD_SERVICE_CHANNEL_TABLES = lOADED_TO_ADJD_SERVICE_CHANNEL_TABLES;
	}
	public int getPENDING_ADJD_CLAIMS() {
		return PENDING_ADJD_CLAIMS;
	}
	public void setPENDING_ADJD_CLAIMS(int pENDING_ADJD_CLAIMS) {
		PENDING_ADJD_CLAIMS = pENDING_ADJD_CLAIMS;
	}
	/*@Override
	public String toString() {
		return "Bean [PROCESS_DATE1=" + PROCESS_DATE1 + ", LOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES="
				+ LOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES + ", LOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES="
				+ LOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES + ", PENDING_PRADJD_CLAIMS=" + PENDING_PRADJD_CLAIMS
				+ ", PROCESS_DATE2=" + PROCESS_DATE2 + ", LOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES="
				+ LOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES + ", LOADED_TO_ADJD_SERVICE_CHANNEL_TABLES="
				+ LOADED_TO_ADJD_SERVICE_CHANNEL_TABLES + ", PENDING_ADJD_CLAIMS=" + PENDING_ADJD_CLAIMS + "]";
	}*/
	
	public String getDataFromObj() {
		return    PROCESS_DATE1 + " "
				+ LOADED_TO_PRADJD_CLAIM_REPOSITORY_TABLES + " "
				+ LOADED_TO_PRADJD_SERVICE_CHANNEL_TABLES + " " 
				+ PENDING_PRADJD_CLAIMS +" "
				+ PROCESS_DATE2 + " "
				+ LOADED_TO_ADJD_CLAIM_REPOSITORY_TABLES + " "
				+ LOADED_TO_ADJD_SERVICE_CHANNEL_TABLES + " " 
				+ PENDING_ADJD_CLAIMS ;
	}
	
	
	
}
